# Generated by Django 5.0 on 2024-03-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experts",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orders_items",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="videos",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="orders_items",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.orders"
            ),
        ),
        migrations.AlterField(
            model_name="orders_items",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.products"
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterModelTable(
            name="experts",
            table="experts",
        ),
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
        migrations.AlterModelTable(
            name="orders_items",
            table="orders_items",
        ),
        migrations.AlterModelTable(
            name="videos",
            table="videos",
        ),
    ]
