# Generated by Django 5.0 on 2024-03-11 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_experts_options_alter_orders_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="background",
        ),
    ]
