# Generated by Django 5.0 on 2024-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_products_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "chatbot",
                "managed": True,
            },
        ),
    ]
