# Generated by Django 5.0 on 2024-03-13 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_chatbot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
    ]
