# Generated by Django 5.0 on 2024-03-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_orders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
    ]
