# Generated by Django 5.0 on 2024-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_categories_alter_products_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("image", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
