# Generated by Django 5.0 on 2024-03-17 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experts",
            name="enable",
        ),
    ]
