# Generated by Django 5.0 on 2024-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_orders_governate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
