# Generated by Django 5.0 on 2024-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experts",
            name="image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
    ]
