# Generated by Django 5.0 on 2024-03-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_alter_experts_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
    ]
