# Generated by Django 5.0 on 2024-03-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_products_image_alter_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experts",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
