# Generated by Django 5.0 on 2024-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_alter_experts_image_alter_products_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="question",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="experts",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orders",
            name="governate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orders",
            name="total",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="videos",
            name="section",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="videos",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
