# Generated by Django 5.0 on 2024-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_alter_categories_title_alter_chatbot_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videos",
            old_name="link",
            new_name="video",
        ),
    ]
